apiVersion: apps/v1
kind: StatefulSet #to get stable name/ip address for each pod which is differnt from replica set
metadata:
  name: mongodb
  namespace: grade-submission
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: mongodb
  serviceName: mongodb  ##mongodb-0 mongodb-1
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grade-submission
        app.kubernetes.io/component: database
        app.kubernetes.io/instance: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4
        envFrom:
          - secretRef:
              name: mongodb-secret
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: monodb-persistent-storage
          mountPath: /data/db
  volumeClaimTemplates: # will create separate volume for each replica pod
  - metadata:
      name: monodb-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
